[package]
name = "error_mapper"
version = "0.2.0"
edition = "2021"
authors = ["Tomas Ponce <nacho.ponce25@gmail.com>"]
keywords = ["error", "handling", "macro", "simple"]
description = "This crate was created to avoid the use of the standard Error, and allow a more simple usage of error handling"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.28"}
lazy_static = "1.4.0"
mysql_async = { version = "0.32.2", features = ["default"]}

[features]
mysql_async = []
full = ["mysql_async"]