[package]
name = "error_mapper"
version = "0.2.2"
edition = "2021"
authors = ["Tomas Ponce <nacho.ponce25@gmail.com>"]
keywords = ["error", "handling", "macro", "simple"]
description = "This crate was created to avoid the use of the standard Error, and allow a more simple usage of error handling"
rust-version = "1.72.0"
readme = "README.md"
repository = "https://github.com/tommyHellraiser/error_mapper"
categories = ["config", "data-structures", "development-tools", "rust-patterns"]
license = "MIT"
license-file = "LICENSE.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.28"}
mysql_async = { version = "0.32.2", features = ["default"]}
tokio = { version = "1.32.0", features = ["full"]}

[features]
full = ["mysql_async", "chrono"]
mysql_async = []
chrono = []